service: convergence

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-2

functions:
  convergence:
    handler: convergence.play
    events:
    - http:
        path: play/{word1}/{word2}
        method: get
        cors: true